cappsrcgen added, lincese updated and readme updated.

diff --git a/cappsrcgen b/cappsrcgen
--- a/cappsrcgen
+++ b/cappsrcgen
@@ -26,43 +26,15 @@
 # Ganesan Umanesan <ganesan.umanesan@seagate.com>
 # 23/01/2017
 
-if [[ "$#" -ne 1 ]]; then
-    echo "illegal number of parameters"
-    echo "$(basename $0) <rpms directory path>"
-    exit
-fi
-
-RPM1=$1mero-1.1*.rpm
-RPM2=$1mero-devel-1.1*.rpm
-
-#mero rpm
-if [ ! -e $RPM1 ]; then
-	echo $RPM1
-	echo "error! mero rpm does not exist"
+IP=$(sudo lctl list_nids)
+if [[ ! ${IP} ]]; then
+	(>&2 echo 'error! m0singlenode not running.')
+	(>&2 echo 'start m0singlenode')
 	exit
 fi
 
-#mero-devel rpm
-if [ ! -e $RPM2 ]; then
-	echo $RPM2
-	echo "error! mero-devel rpm does not exist"
-	exit
-fi
-
-
-#stop mero
-sudo m0singlenode stop
-
-#remove existing mero
-sudo yum remove -y mero mero-devel
-sudo rm -rf /etc/mero/ /var/mero
-
-#install new mero
-sudo yum install -y $RPM1 $RPM2
-sudo m0singlenode activate
-sudo m0setup -cv
-sudo m0setup -Mv
-
-#start mero
-sudo m0singlenode start
-
+echo ${IP}:12345:44:101
+echo ${IP}:12345:45:1
+echo '<0x7000000000000001:0>'
+echo '<0x7200000000000000:0>' 
+echo '/tmp/' 
